apiVersion: v1
kind: Secret
type: generic
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "ecr-renew-token.labels" . | nindent 4 }}
data:
  AWS_ACCESS_KEY_ID: {{ .Values.aws.access_key_id | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secret_access_key | b64enc }}
  AWS_REGION: {{ .Values.aws.aws_region | b64enc }}
  AWS_DEFAULT_REGION: {{ .Values.aws.aws_region | b64enc }}
